var biblioteca = [
    "Roberto Bolanos",
    "Carlos Villagran",
    "Ramon Valdes",
    "Ruben Aguirre",
    "Florinda Meza",
    "Maria Antonieta",
    "Angelines Fernandes",
    "Edgar Vivar",
    "Nhonho",
    "Popis",
    "Raul Padilla",
    "Dona Neves",
    "Horacio Gomez",
    "Regina Torne",
    "Ana Lilian",
    "Ricardo de Pascual",
    "Chapolin",
    "Malicha",
    "Seu Madroga",
    "Doutor Chapatin",
]

var dicas = [
    "Chaves",
    "Kiko",
    "Seu Madruga",
    "Professor Girafales",
    "Dona Florinda",
    "Chiquinha",
    "Bruxa do 71",
    "Senhor Barriga",
    "Edgar Vivar",
    "Florinda Meza",
    "Jaiminho Carteiro",
    "Maria Antonieta de Las Nieves",
    "Godines",
    "Gloria",
    "Paty",
    "Seu Furtado",
    "Roberto Gomez Bolanos",
    "Afilhada do Seu Madruga",
    "Primo do Seu Madruga",
    "Roberto Gomez Bolanos",
]